// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ZXklYJTt5iK6HIZKJPrsRmjTcbNobo4',
    appId: '1:194113660858:web:80fd5362f95387e4319f83',
    messagingSenderId: '194113660858',
    projectId: 'myopia-d27be',
    authDomain: 'myopia-d27be.firebaseapp.com',
    storageBucket: 'myopia-d27be.appspot.com',
    measurementId: 'G-GSXG9X09R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoU7q1q20wlcIohVhhX_Pe08LQlIXZXg',
    appId: '1:194113660858:android:93a67f0b6ac4efc9319f83',
    messagingSenderId: '194113660858',
    projectId: 'myopia-d27be',
    storageBucket: 'myopia-d27be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWiu7HgcZ57w_UzmeWQ5eKD9ZYZUvzBUk',
    appId: '1:194113660858:ios:818d31b926ba4351319f83',
    messagingSenderId: '194113660858',
    projectId: 'myopia-d27be',
    storageBucket: 'myopia-d27be.appspot.com',
    iosBundleId: 'com.example.myopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWiu7HgcZ57w_UzmeWQ5eKD9ZYZUvzBUk',
    appId: '1:194113660858:ios:8093038759c58d93319f83',
    messagingSenderId: '194113660858',
    projectId: 'myopia-d27be',
    storageBucket: 'myopia-d27be.appspot.com',
    iosBundleId: 'com.example.myopia.RunnerTests',
  );
}
